### ISSUE TITLE
Inaccessible Port. Unable to access mattermost-preview

### ISSUE THREAD

**Issue by 0006mathew** [mattermost/mattermost-docker-preview#4]
**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.767 GiB
Name: warmachine
ID: REDACTED
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Steps to reproduce the issue:**
1. docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview

**Describe the results you received:**
I cannot access the 8065 port via localhost.
```
curl localhost:8065
curl: (56) Recv failure: Connection reset by peer
```

**Describe the results you expected:**
localhost:8065 should be accessible via browser.

**Additional information you deem important (e.g. issue happens only occasionally):**
docker inspect mattermost-preview
https://gist.github.com/0006mathew/921e560e6ce1f13d8fded53535912ec6

**Comment by joelnb** [comment]
I am having this same issue but it does seem like Mattermost is listening on the correct port but is not accessible from outside the container due to only listening ipv6.

```
$ docker run --name mattermost-preview -d --publish 8065:8065 mattermost/mattermost-preview
df152d8da7203e5144053be41f40aa6da4239a908930cd4e4d8e18140d44ce7d
$ docker exec -it mattermost-preview bash
root@df152d8da720:/mm# apt-get update && apt-get install net-tools curl
...
root@df152d8da720:/mm# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::8065                 :::*                    LISTEN      132/platform    
tcp6       0      0 :::3306                 :::*                    LISTEN      -               
root@df152d8da720:/mm# curl localhost:8065
<!DOCTYPE html> <html> <head> <meta http-equiv=X-UA-Compatible content="IE=edge"> <meta name=viewport content="width=device-width,initial-scale=1,maximum-scale=1"> <meta name=robots content="noindex, nofollow"> <meta name=referrer content=no-referrer> <title>Mattermost</title> <meta name=apple-mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-status-bar-style content=default> <meta name=mobile-web-app-capable content=yes> <meta name=apple-mobile-web-app-title content=Mattermost> <meta name=application-name content=Mattermost> <meta name=format-detection content="telephone=no"> <link rel=apple-touch-icon sizes=57x57 href=/static/files/2a1c469aec4e9dc611d8ff21211b350a.png> <link rel=apple-touch-icon sizes=60x60 href=/static/files/5f235d262658c900615681530b29f56d.png> <link rel=apple-touch-icon sizes=72x72 href=/static/files/32a23a3581becc08838c1c1fed2f6906.png> <link rel=apple-touch-icon sizes=76x76 href=/static/files/1731ddbbe8acf47fca84c4b587dccee5.png> <link rel=apple-touch-icon sizes=144x144 href=/static/files/d286c202041de6ff330bab474f24f8da.png> <link rel=apple-touch-icon sizes=120x120 href=/static/files/5805c6d344fdf7f5443307ff8fafa324.png> <link rel=apple-touch-icon sizes=152x152 href=/static/files/89d5e1a1cc8e97dffbb97f5f8f80a0b9.png> <link rel=icon type=image/png sizes=16x16 href=/static/files/10ee7f4daf66060a2af9c5eef914b4c8.png> <link rel=icon type=image/png sizes=32x32 href=/static/files/02100a5664ea1bf9e4990ad37936af4a.png> <link rel=icon type=image/png sizes=96x96 href=/static/files/3d9b3740060310158cf259a1c2c0ddc9.png> <link rel=icon type=image/png sizes=192x192 href=/static/files/f3ee0663271515c7f6aeb4b8f47d5c12.png> <link rel=manifest href=/static/config/manifest.json> <link rel=stylesheet class=code_theme> <style id=antiClickjack>body{display:none!important}</style> <script src=/static/bundle-3.0.3.js></script> <script>if(self===top){var blocker=document.getElementById("antiClickjack");blocker.parentNode.removeChild(blocker)}</script> </head> <body> <div id=root> <div class=loading-screen style=""> <div class=loading__content> <div class="round round-1"></div> <div class="round round-2"></div> <div class="round round-3"></div> </div> </div> </div> <script>window.setup_root()</script> </body> </html>
root@df152d8da720:/mm#
```

**Comment by joelnb** [comment]
I think I was wrong before. Seems to be something odd going on with the port forward docker uses - I can access Mattermost on the IP of the container, just not via the port forward. Can you try that?

You can find the IP of the container with:
```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' mattermost-preview
```

**Comment by 0006mathew** [comment]
I followed your steps and for netstat -tulpn
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp6       0      0 :::3306                 :::*                    LISTEN      -               
```
the docker inspect command produced this
```
$ docker inspect --format '{{ .NetworkSettings.IPAddress }}' mattermost-preview
172.17.0.2
mathew@warmachine:~$ curl 172.17.0.2:8065
curl: (7) Failed to connect to 172.17.0.2 port 8065: Connection refused
```

**Comment by joelnb** [comment]
Oh right, looks like your issue is different then - in your case Mattermost doesn't seem to be listening at all. Can you post the output of `docker logs mattermost-preview`?

**Comment by 0006mathew** [comment]
docker logs mattermost-preview
```
starting mysql
Initializing database
2016-06-19T13:24:59.604444Z 0 [Warning] InnoDB: New log files created, LSN=45790
2016-06-19T13:25:00.134892Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
2016-06-19T13:25:00.380530Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 3941acb9-3621-11e6-b21c-0242ac110002.
2016-06-19T13:25:00.438033Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
2016-06-19T13:25:00.439104Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
2016-06-19T13:25:15.918776Z 1 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:15.918820Z 1 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:15.918846Z 1 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:15.918879Z 1 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:15.918950Z 1 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
starting platform
[13:25:17 UTC 2016/06/19] [INFO] (github.com/mattermost/platform/utils.GetTranslationsBySystemLocale:56) Loaded system translations for 'en' from '/mm/mattermost/i18n/en.json'
[2016/06/19 13:25:17 UTC] [INFO] Current version is 3.0.0 (3.0.3/Fri May 27 18:08:10 UTC 2016/cb745475452a9fc8ef3a9fedf6b34af7d05adba9)
[2016/06/19 13:25:17 UTC] [INFO] Enterprise Enabled: false
[2016/06/19 13:25:17 UTC] [INFO] Current working directory is /mm/mattermost
[2016/06/19 13:25:17 UTC] [INFO] Loaded config file from /mm/mattermost/config/config_docker.json
[2016/06/19 13:25:17 UTC] [INFO] Server is initializing...
[2016/06/19 13:25:17 UTC] [INFO] Pinging sql master database
[2016/06/19 13:25:17 UTC] [CRIT] Failed to ping db err:dial tcp [::1]:3306: getsockopt: connection refused
panic: Failed to open sql connection dial tcp [::1]:3306: getsockopt: connection refused

goroutine 1 [running]:
panic(0xb68f00, 0xc820272910)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/mattermost/platform/store.setupConnection(0xd8a010, 0x6, 0xc8202895e0, 0x5, 0xc820243450, 0x47, 0xa, 0xa, 0xc820272200, 0x7f4204b8a4b0)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:218 +0x894
github.com/mattermost/platform/store.initConnection(0x41c201)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:63 +0x11b
github.com/mattermost/platform/store.NewSqlStore(0x0, 0x0)
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/store/sql_store.go:85 +0x49
github.com/mattermost/platform/api.NewServer()
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/api/server.go:36 +0xe8
main.main()
	/var/lib/jenkins/jobs/mattermost-platform-release/workspace/src/github.com/mattermost/platform/mattermost.go:97 +0x967
Database initialized
MySQL init process in progress...
2016-06-19T13:25:23.362566Z 0 [Note] mysqld (mysqld 5.7.12) starting as process 60 ...
2016-06-19T13:25:23.368514Z 0 [Note] InnoDB: PUNCH HOLE support available
2016-06-19T13:25:23.368558Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2016-06-19T13:25:23.368564Z 0 [Note] InnoDB: Uses event mutexes
2016-06-19T13:25:23.368569Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2016-06-19T13:25:23.368576Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
2016-06-19T13:25:23.368583Z 0 [Note] InnoDB: Using Linux native AIO
2016-06-19T13:25:23.368940Z 0 [Note] InnoDB: Number of pools: 1
2016-06-19T13:25:23.369081Z 0 [Note] InnoDB: Using CPU crc32 instructions
2016-06-19T13:25:23.384542Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2016-06-19T13:25:23.401339Z 0 [Note] InnoDB: Completed initialization of buffer pool
2016-06-19T13:25:23.403734Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2016-06-19T13:25:23.416110Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2016-06-19T13:25:23.508492Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2016-06-19T13:25:23.508590Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2016-06-19T13:25:23.679359Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2016-06-19T13:25:23.681364Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2016-06-19T13:25:23.681387Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2016-06-19T13:25:23.681864Z 0 [Note] InnoDB: Waiting for purge to start
2016-06-19T13:25:23.732233Z 0 [Note] InnoDB: 5.7.12 started; log sequence number 2522792
2016-06-19T13:25:23.732929Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2016-06-19T13:25:23.733172Z 0 [Note] Plugin 'FEDERATED' is disabled.
2016-06-19T13:25:23.737322Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2016-06-19T13:25:23.737516Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160619 13:25:23
2016-06-19T13:25:23.783066Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:23.783122Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:23.783168Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:23.783192Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:23.785284Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:23.793472Z 0 [Note] Event Scheduler: Loaded 0 events
2016-06-19T13:25:23.793707Z 0 [Note] mysqld: ready for connections.
Version: '5.7.12'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server (GPL)
Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
2016-06-19T13:25:31.432540Z 4 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:31.432568Z 4 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:31.432617Z 4 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
2016-06-19T13:25:31.456339Z 8 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:31.456367Z 8 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:31.456578Z 8 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.

/entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2016-06-19T13:25:31.457877Z 0 [Note] Giving 0 client threads a chance to die gracefully
2016-06-19T13:25:31.457900Z 0 [Note] Shutting down slave threads
2016-06-19T13:25:31.457908Z 0 [Note] Forcefully disconnecting 0 remaining clients
2016-06-19T13:25:31.457914Z 0 [Note] Event Scheduler: Purging the queue. 0 events
2016-06-19T13:25:31.457971Z 0 [Note] Binlog end
2016-06-19T13:25:31.458827Z 0 [Note] Shutting down plugin 'ngram'
2016-06-19T13:25:31.458847Z 0 [Note] Shutting down plugin 'BLACKHOLE'
2016-06-19T13:25:31.458853Z 0 [Note] Shutting down plugin 'partition'
2016-06-19T13:25:31.458858Z 0 [Note] Shutting down plugin 'ARCHIVE'
2016-06-19T13:25:31.458863Z 0 [Note] Shutting down plugin 'MEMORY'
2016-06-19T13:25:31.458871Z 0 [Note] Shutting down plugin 'INNODB_SYS_VIRTUAL'
2016-06-19T13:25:31.458878Z 0 [Note] Shutting down plugin 'INNODB_SYS_DATAFILES'
2016-06-19T13:25:31.458883Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESPACES'
2016-06-19T13:25:31.458887Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN_COLS'
2016-06-19T13:25:31.458912Z 0 [Note] Shutting down plugin 'INNODB_SYS_FOREIGN'
2016-06-19T13:25:31.458918Z 0 [Note] Shutting down plugin 'INNODB_SYS_FIELDS'
2016-06-19T13:25:31.458922Z 0 [Note] Shutting down plugin 'INNODB_SYS_COLUMNS'
2016-06-19T13:25:31.458927Z 0 [Note] Shutting down plugin 'INNODB_SYS_INDEXES'
2016-06-19T13:25:31.458932Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLESTATS'
2016-06-19T13:25:31.458936Z 0 [Note] Shutting down plugin 'INNODB_SYS_TABLES'
2016-06-19T13:25:31.458944Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_TABLE'
2016-06-19T13:25:31.458948Z 0 [Note] Shutting down plugin 'INNODB_FT_INDEX_CACHE'
2016-06-19T13:25:31.458953Z 0 [Note] Shutting down plugin 'INNODB_FT_CONFIG'
2016-06-19T13:25:31.458957Z 0 [Note] Shutting down plugin 'INNODB_FT_BEING_DELETED'
2016-06-19T13:25:31.458962Z 0 [Note] Shutting down plugin 'INNODB_FT_DELETED'
2016-06-19T13:25:31.458969Z 0 [Note] Shutting down plugin 'INNODB_FT_DEFAULT_STOPWORD'
2016-06-19T13:25:31.458973Z 0 [Note] Shutting down plugin 'INNODB_METRICS'
2016-06-19T13:25:31.458978Z 0 [Note] Shutting down plugin 'INNODB_TEMP_TABLE_INFO'
2016-06-19T13:25:31.458984Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_POOL_STATS'
2016-06-19T13:25:31.458989Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE_LRU'
2016-06-19T13:25:31.458993Z 0 [Note] Shutting down plugin 'INNODB_BUFFER_PAGE'
2016-06-19T13:25:31.458998Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX_RESET'
2016-06-19T13:25:31.459005Z 0 [Note] Shutting down plugin 'INNODB_CMP_PER_INDEX'
2016-06-19T13:25:31.459010Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM_RESET'
2016-06-19T13:25:31.459017Z 0 [Note] Shutting down plugin 'INNODB_CMPMEM'
2016-06-19T13:25:31.459022Z 0 [Note] Shutting down plugin 'INNODB_CMP_RESET'
2016-06-19T13:25:31.459027Z 0 [Note] Shutting down plugin 'INNODB_CMP'
2016-06-19T13:25:31.459031Z 0 [Note] Shutting down plugin 'INNODB_LOCK_WAITS'
2016-06-19T13:25:31.459038Z 0 [Note] Shutting down plugin 'INNODB_LOCKS'
2016-06-19T13:25:31.459042Z 0 [Note] Shutting down plugin 'INNODB_TRX'
2016-06-19T13:25:31.459047Z 0 [Note] Shutting down plugin 'InnoDB'
2016-06-19T13:25:31.459128Z 0 [Note] InnoDB: FTS optimize thread exiting.
2016-06-19T13:25:31.459221Z 0 [Note] InnoDB: Starting shutdown...
2016-06-19T13:25:31.559614Z 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
2016-06-19T13:25:31.583499Z 0 [Note] InnoDB: Buffer pool(s) dump completed at 160619 13:25:31
2016-06-19T13:25:33.529961Z 0 [Note] InnoDB: Shutdown completed; log sequence number 12128369
2016-06-19T13:25:33.532956Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
2016-06-19T13:25:33.532977Z 0 [Note] Shutting down plugin 'MyISAM'
2016-06-19T13:25:33.532987Z 0 [Note] Shutting down plugin 'MRG_MYISAM'
2016-06-19T13:25:33.532994Z 0 [Note] Shutting down plugin 'CSV'
2016-06-19T13:25:33.533011Z 0 [Note] Shutting down plugin 'PERFORMANCE_SCHEMA'
2016-06-19T13:25:33.533043Z 0 [Note] Shutting down plugin 'sha256_password'
2016-06-19T13:25:33.533050Z 0 [Note] Shutting down plugin 'mysql_native_password'
2016-06-19T13:25:33.533223Z 0 [Note] Shutting down plugin 'binlog'
2016-06-19T13:25:33.533851Z 0 [Note] mysqld: Shutdown complete


MySQL init process done. Ready for start up.

2016-06-19T13:25:33.743953Z 0 [Note] mysqld (mysqld 5.7.12) starting as process 7 ...
2016-06-19T13:25:33.749017Z 0 [Note] InnoDB: PUNCH HOLE support available
2016-06-19T13:25:33.749049Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2016-06-19T13:25:33.749054Z 0 [Note] InnoDB: Uses event mutexes
2016-06-19T13:25:33.749058Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2016-06-19T13:25:33.749066Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
2016-06-19T13:25:33.749075Z 0 [Note] InnoDB: Using Linux native AIO
2016-06-19T13:25:33.749443Z 0 [Note] InnoDB: Number of pools: 1
2016-06-19T13:25:33.749594Z 0 [Note] InnoDB: Using CPU crc32 instructions
2016-06-19T13:25:33.761957Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2016-06-19T13:25:33.773430Z 0 [Note] InnoDB: Completed initialization of buffer pool
2016-06-19T13:25:33.775800Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2016-06-19T13:25:33.787953Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2016-06-19T13:25:33.845921Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2016-06-19T13:25:33.846020Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2016-06-19T13:25:34.068658Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2016-06-19T13:25:34.069606Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2016-06-19T13:25:34.069620Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2016-06-19T13:25:34.070007Z 0 [Note] InnoDB: Waiting for purge to start
2016-06-19T13:25:34.120233Z 0 [Note] InnoDB: 5.7.12 started; log sequence number 12128369
2016-06-19T13:25:34.120850Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2016-06-19T13:25:34.121236Z 0 [Note] Plugin 'FEDERATED' is disabled.
2016-06-19T13:25:34.125729Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
2016-06-19T13:25:34.125765Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2016-06-19T13:25:34.125845Z 0 [Note] IPv6 is available.
2016-06-19T13:25:34.125897Z 0 [Note]   - '::' resolves to '::';
2016-06-19T13:25:34.125961Z 0 [Note] Server socket created on IP: '::'.
2016-06-19T13:25:34.128686Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160619 13:25:34
2016-06-19T13:25:34.182263Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:34.182469Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:34.187420Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2016-06-19T13:25:34.195856Z 0 [Note] Event Scheduler: Loaded 0 events
2016-06-19T13:25:34.196027Z 0 [Note] mysqld: ready for connections.
Version: '5.7.12'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
```

**Comment by joelnb** [comment]
Ah, in your case mysql is not yet ready at the time when mattermost starts. If you want a hacky solution which will get you going (pending a more correct solution) then your best bet is to clone this repo, cd into the directory, edit the file `docker-entry.sh` and change the line `sleep 20` to something higher. After you have done that you should be able to do:

```
docker build -t 0006mathew/mattermost .
docker run --name mattermost-preview -d --publish 8065:8065 0006mathew/mattermost
```

I've never used Mattermost but I will have a think about a proper way of handling this & make a pull request if I think of something elegant.

**Comment by 0006mathew** [comment]
You mean clone or fork? If I clone it to a local directory. What is the need for 0006mathew/mattermost

**Comment by joelnb** [comment]
I mean clone. I just used the name 0006matthew/mattermost so that you don't end up replacing the default version with your one. You could replace that with any string as long as it is the same in both commands.

**Comment by 0006mathew** [comment]
Thanks.I will update as soon as I do that.

**Comment by joelnb** [comment]
Yeah, I really have no idea about why it doesn't like 'localhost' because I'm sure it sometimes responds fine when accessing via that name.

I have made a pull request which I believe solves the issue (https://github.com/mattermost/mattermost-docker-preview/pull/5) so it would be awesome if you could check that out. I've also pushed it to [docker hub](https://hub.docker.com/r/joelnb/mattermost) but not sure if you'll be okay running it from there when you can't verify what is included (I haven't setup builds or anything, just pushed my local version).
